#!/bin/sh
#/etc/init.d/netdromm
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
 start)
  cd /opt/netdromm/
  npm start
  ;;
 stop)
  ;;
*)
echo "Usage: /etc/init.d/netdromm {start|stop}"
exit 1
;;
esac
exit 0
